name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      -
        name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false # 移除推送操作
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      -
        name: Save Docker image
        run: |
          docker save ${{ steps.meta.outputs.tags }} > chatgpt-next-web.tar
      
      -
        name: Output image information
        run: |
          echo "Image tags: ${{ steps.meta.outputs.tags }}"
          echo "Image labels: ${{ steps.meta.outputs.labels }}"
          echo "Image saved to: chatgpt-next-web.tar"
